---
- name: Set up Jenkins service account in Kubernetes and prepare kubeconfig
  hosts: master
  become: true
  tasks:
    - name: Create Jenkins service account
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: jenkins
            namespace: default

    - name: Create ClusterRoleBinding for Jenkins
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: jenkins
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
          - kind: ServiceAccount
            name: jenkins
            namespace: default

    - name: Generate token for Jenkins service account
      shell: |
        kubectl create token jenkins -n default --duration=24h
      register: token_output

    - name: Create secret with token and CA certificate
      shell: |
        kubectl create secret generic jenkins-secret --namespace default --from-literal=token={{ token_output.stdout }} --from-file=ca.crt=/etc/kubernetes/pki/ca.crt

    - name: Patch the Jenkins service account to use the secret
      shell: |
        kubectl patch serviceaccount jenkins -n default -p '{"secrets": [{"name": "jenkins-secret"}]}'

    - name: Create kubeconfig file for Jenkins
      shell: |
        cat <<EOF > /tmp/kubeconfig-jenkins.yaml
        apiVersion: v1
        kind: Config
        clusters:
        - cluster:
            certificate-authority-data: $(kubectl get secret jenkins-secret -n default -o jsonpath="{.data['ca\.crt']}")
            server: $(kubectl config view --minify -o jsonpath="{.clusters[0].cluster.server}")
          name: kubernetes
        contexts:
        - context:
            cluster: kubernetes
            namespace: default
            user: jenkins
          name: jenkins
        current-context: jenkins
        users:
        - name: jenkins
          user:
            token: {{ token_output.stdout }}
        EOF

    - name: Ensure the kubeconfig file is readable
      file:
        path: /tmp/kubeconfig-jenkins.yaml
        mode: '0644'