replicas: 1
minimumMasterNodes: 1

ingress:
  enabled: true
  hosts:
    - host: localhost
      paths:
        - path: /

volumeClaimTemplates:
  - metadata:
      name: elasticsearch-master
      labels:
        app: elasticsearch-master
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      selector:
        matchLabels:
          app: elasticsearch-master
      volumeMode: Filesystem

resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 1Gi
    cpu: 1

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

extraEnvs:
  - name: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"
  - name: path.data
    value: /usr/share/elasticsearch/data

persistence:
  enabled: true
  existingClaim: pvc-elasticsearch