variable "ami" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "security_group_id" {}
variable "key_name" {}
variable "associate_public_ip_address" {}
variable "iam_instance_profile" {}
variable "provision_command" {}
variable "tags" {}
