---
- name: Deploy Docker Containers
  hosts: all
  become: yes
  tasks:
    - name: Copy deploy.sh script to the target servers
      copy:
        src: /root/project/devops/deploy.sh
        dest: /home/ec2-user/deploy.sh
        mode: '0755'

    - name: Create directory for configuration file if it doesn't exist
      file:
        path: /home/ec2-user/applications/solana-spl-momentum-scanner
        state: directory
        mode: '0755'

    - name: Copy configuration file to the target servers
      copy:
        src: /root/project/devops/applications/solana-spl-momentum-scanner/config.json
        dest: /home/ec2-user/applications/solana-spl-momentum-scanner/config.json
        mode: '0644'

    - name: Execute deploy.sh script and log output
      shell: |
        /home/ec2-user/deploy.sh {{ app_name }} {{ dockerhub_repo }} {{ tag }} {{ service }} {{ config_file }} > /home/ec2-user/deploy.log 2>&1
      args:
        executable: /bin/bash