---
- name: Install and setup k3s worker node
  hosts: worker
  become: yes

  vars:
    master_ip: "13.51.102.35"  # Replace with your master node's IP address
    node_token: "K108f79877ab47e0466522e56cbae12b7c571133ffc23d5fa1fbc777b949051de57::server:7e33a6a791116f3f1411aca243e6851e"  # Replace with the token retrieved from the master node

  tasks:
    - name: Copy k3s installation script to remote server
      copy:
        src: /root/project/devops/kubernetes/install_k3s_worker.sh
        dest: /tmp/install_k3s_worker.sh
        mode: '0755'

    - name: Run k3s installation script
      shell: /tmp/install_k3s_worker.sh {{ master_ip }} {{ node_token }}
      args:
        executable: /bin/bash

    - name: Ensure k3s agent is running
      shell: systemctl is-active --quiet k3s-agent && echo k3s-agent is running || echo k3s-agent is not running
      register: k3s_agent_status
      ignore_errors: true

    - name: Debug k3s agent status
      debug:
        var: k3s_agent_status.stdout

    - name: Check k3s agent service
      systemd:
        name: k3s-agent
        state: started
        enabled: yes
      when: k3s_agent_status.stdout == "k3s-agent is not running"