---
- name: Install Kubernetes on EC2 instances
  hosts: all
  become: true
  tasks:
    - name: Add Kubernetes repository
      yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: no

    - name: Disable SELinux
      command: setenforce 0
      ignore_errors: true

    - name: Permanently disable SELinux in config file
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=enforcing'
        replace: 'SELINUX=disabled'

    - name: Install Kubernetes components
      yum:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        disable_gpg_check: yes
      notify:
        - Enable and start kubelet

  handlers:
    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started