---
- name: Copy test.txt to EC2 instances
  hosts: all
  become: yes
  tasks:
    - name: Copy test.txt file to /home/ec2-user
      copy:
        src: /root/project/devops/ansible/test.txt
        dest: /home/ec2-user/test.txt
        mode: '0644'