---
- name: Copy deploy.sh script to the target servers
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Copy deploy.sh script to /home/ec2-user
      copy:
        src: /root/project/devops/ansible/deploy.sh
        dest: /home/ec2-user/deploy.sh
        mode: '0755'