---
- name: Cleanup Prometheus, Grafana, and Helm
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
    - name: Uninstall Prometheus
      shell: helm uninstall prometheus -n logging
      ignore_errors: yes

    - name: Uninstall Grafana
      shell: helm uninstall grafana -n logging
      ignore_errors: yes

    - name: Delete logging namespace
      shell: kubectl delete namespace logging
      ignore_errors: yes

    - name: Delete all PVCs in logging namespace
      shell: kubectl delete pvc -n logging --all
      ignore_errors: yes

    - name: Remove Helm (Ubuntu)
      apt:
        name: helm
        state: absent
      when: ansible_os_family == "Debian"
      ignore_errors: yes

    - name: Remove Helm (CentOS/RHEL)
      yum:
        name: helm
        state: absent
      when: ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Remove Helm configuration and cache
      file:
        path: ~/.helm
        state: absent
      ignore_errors: yes

    - name: Delete Prometheus operator cluster role
      shell: kubectl delete clusterrole prometheus-operator
      ignore_errors: yes

    - name: Delete Prometheus operator cluster role binding
      shell: kubectl delete clusterrolebinding prometheus-operator
      ignore_errors: yes

    - name: Delete Grafana cluster role binding
      shell: kubectl delete clusterrolebinding grafana
      ignore_errors: yes

    - name: Delete Prometheus CRDs
      shell: >
        kubectl delete crd prometheuses.logging.coreos.com &&
        kubectl delete crd alertmanagers.logging.coreos.com &&
        kubectl delete crd prometheusrules.logging.coreos.com &&
        kubectl delete crd servicemonitors.logging.coreos.com &&
        kubectl delete crd podmonitors.logging.coreos.com &&
        kubectl delete crd thanosrulers.logging.coreos.com
      ignore_errors: yes