---
- name: Setup Kubernetes Cluster
  hosts: master
  become: yes

  tasks:
    - name: Get public IP using curl
      command: curl -s ifconfig.me
      register: public_ip

    - name: Set master public IP fact
      set_fact:
        master_public_ip: "{{ public_ip.stdout }}"

    - name: Print public IP
      debug:
        msg: "The public IP of the target server is: {{ master_public_ip }}"    

    - name: Update all packages
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Disable swap
      command: swapoff -a

    - name: Load kernel modules
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load kernel modules immediately
      command: modprobe overlay
    - command: modprobe br_netfilter

    - name: Set system configurations for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl params without reboot
      command: sysctl --system

    - name: Install containerd
      block:
        - name: Download containerd
          get_url:
            url: "https://github.com/containerd/containerd/releases/download/v1.6.2/containerd-1.6.2-linux-amd64.tar.gz"
            dest: "/tmp/containerd-1.6.2-linux-amd64.tar.gz"

        - name: Extract containerd
          unarchive:
            src: "/tmp/containerd-1.6.2-linux-amd64.tar.gz"
            dest: "/usr/local"
            remote_src: yes

        - name: Install containerd service
          get_url:
            url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
            dest: "/etc/systemd/system/containerd.service"

        - name: Enable and start containerd
          systemd:
            name: containerd
            enabled: yes
            state: started

    - name: Install runc
      block:
        - name: Download runc
          get_url:
            url: "https://github.com/opencontainers/runc/releases/download/v1.1.9/runc.amd64"
            dest: "/usr/local/sbin/runc"
            mode: '0755'

    - name: Install CNI plugins
      block:
        - name: Create directory for CNI plugins
          file:
            path: /opt/cni/bin
            state: directory
            mode: '0755'

        - name: Download CNI plugins
          get_url:
            url: "https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz"
            dest: "/tmp/cni-plugins-linux-amd64-v1.1.1.tgz"

        - name: Extract CNI plugins
          unarchive:
            src: "/tmp/cni-plugins-linux-amd64-v1.1.1.tgz"
            dest: "/opt/cni/bin"
            remote_src: yes

    - name: Configure containerd
      block:
        - name: Create containerd config directory
          file:
            path: /etc/containerd
            state: directory

        - name: Generate default containerd config
          shell: "containerd config default | tee /etc/containerd/config.toml"

        - name: Update containerd config
          replace:
            path: /etc/containerd/config.toml
            regexp: 'SystemdCgroup = false'
            replace: 'SystemdCgroup = true'

        - name: Set sandbox image in containerd config
          replace:
            path: /etc/containerd/config.toml
            regexp: '^(\s*sandbox_image\s*=\s*).+"k8s.gcr.io/pause:3.6"'
            replace: '\1"registry.k8s.io/pause:3.2"'

        - name: Restart containerd
          systemd:
            name: containerd
            state: restarted

    - name: Set SELinux to permissive mode
      block:
        - name: Set SELinux in permissive mode
          selinux:
            policy: targeted
            state: permissive

        - name: Ensure SELinux is in permissive mode on reboot
          replace:
            path: /etc/selinux/config
            regexp: '^SELINUX=enforcing'
            replace: 'SELINUX=permissive'

    - name: Add Kubernetes yum repository without exclude
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key

    - name: Install Kubernetes packages
      dnf:
        name: 
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Add exclude parameter to Kubernetes yum repository
      lineinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        regexp: '^exclude='
        line: 'exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni'
        insertafter: 'gpgkey=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key'    

    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: yes

    - name: Install iproute-tc package
      dnf:
        name: iproute-tc
        state: present

    - name: Ensure the hostname is resolvable
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"

    - name: Pre-pull Kubernetes images
      command: kubeadm config images pull --kubernetes-version v1.30.2
 

    - name: Initialize Kubernetes cluster
      command: kubeadm init --control-plane-endpoint="{{ master_public_ip }}" --apiserver-cert-extra-sans="{{ master_public_ip }}" --pod-network-cidr="10.244.0.0/16" --node-name "master" --ignore-preflight-errors=Swap,ImagePull --kubernetes-version v1.30.2
      ignore_errors: yes

    - name: Configure kubectl for the master node
      shell: |
        sudo mkdir -p /root/.kube
        sudo cp -i /etc/kubernetes/admin.conf /root/.kube/config
        sudo chown $(id -u):$(id -g) /root/.kube/config
        export KUBECONFIG=/root/.kube/config
        kubectl get nodes
      become: yes  

    - name: Apply Calico network plugin
      shell: |
        kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Retrieve join command for worker nodes
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Retrieve worker join command
      shell: |
        kubeadm token create --print-join-command > /tmp/join_command.sh

    - name: Pull the join command to the admin server using public IP
      delegate_to: localhost
      shell: |
        scp -i /home/ec2-user/.ssh/my-key-pair ec2-user@{{ master_public_ip }}:/tmp/join_command.sh /home/ec2-user/infrastructure/devops_setup/terraform/join_command.sh
      register: fetch_result