apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: <CA>
    server: https://<PUBLIC_IP>:6443
  name: k3s
contexts:
- context:
    cluster: k3s
    namespace: default
    user: jenkins
  name: jenkins
current-context: jenkins
users:
- name: jenkins
  user:
    token: <TOKEN>