apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch
  labels:
    app: elasticsearch-master
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/elasticsearch