apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: elasticsearch